@startuml
skinparam classAttributeIconSize 0

package "miembro" #DDDDDD {
    class Persona {
    -nombre: String
    -apellido: String
    -nroDocumento: String
    -tipoDocumento: TipoDocumento
    -ubicacion: Hogar
    -usuario: Usuario
    }

    class Miembro {
    -persona: Persona
    -area: Area
    -areaPendiente: Area
    -tramos: [Tramo]
    -valoresHCMensuales: [ValorHCMensualMiembro]


    +double calcularHuellaCarbonoMiembroMensual(int, int)
    +double calcularHuellaCarbonoMiembroAnual(int)
    +double impactoMiembroEnOrganizacionAnual(int)
    +double impactoMiembroEnOrganizacionMensual(int, int)
    -void agregarHCMensual(int, int, double)
    }

    enum TipoDocumento {
    DNI,
    LE,
    LC
    }
}

package "sector" #DDDDDD {

  abstract class Sector {

  +String getNombre()
  +String nombrePrvoincia()

  }
  note right: El modelo de la API está en su propio DC

  class ProvinciaSector extends Sector {
  -nombre:String
  -pais: PaisSector
  -provinciaCodigo: Long
  }

  class MunicipioSector extends Sector {
  -nombre: String
  -provincia: ProvinciaSector
  -municipioCodigo: Long
  }

  class PaisSector {
  -nombre: String
  }

  class LocalidadSector {
  -nombre: String
  -codPostal: String
  -municipio: MunicipioSector
  }

}

package "organizacion" #DDDDDD {

    class Contacto {
    -mail: String
    -numeroTelefono: String
    }

    class Organizacion {
    -razonSocial: String
    -tipo: TipoOrganizacion
    -clasificacion: Clasificacion
    -sectores: [Area]
    -contactos: [Contacto]
    -medioNotificacion: MedioNotificacion
    -datosDeLaActividad: [DatoDeLaActividad]
    -valoresMensuales:[ValorHCMensualOrganizacion]
    -organizacionService: OrganizacionService
    -usuario: usuarioOrganizacion

    +double calcularHuellaCarbonoTotalAnio(int)
    +double calcularHuellaCarbonoTotalMensual(int, int)
    +boolean tieneArea(Area)
    +void enviarRecomendacion()
    }

    class OrganizacionService {
    -transformador: Transformador
    -calculadoraHCActividad: CalculadoraHCActividad

    +void cargarDatosActividad(String, Organizacion)
    +double calcularHuellaCarbonoTotalAnio(int, Organizacion)
    +double calcularHuellaCarbonoTotalMensual(int, int, Organizacion)
    }

    class Area {
    -nombre: String
    -miembros: [Miembro]
    -miembrosPendientes: [Miembro]
    -ubicacion: EspacioDeTrabajo
    -trayectosRegistrados: [Trayecto]
    -trayectosPendientes: [Trayecto]

    +void aceptarVinculacion(Trayecto)
    +double calcularHuellaCarbonoTotalAreaAnual(int)
    +double calcularHuellaCarbonoTotalAreaMensual(int, int)
    +double calcularHuellaCarbonoPromedioMiembroMensual(int, int)
    +double calcularHuellaCarbonoPromedioMiembroAnual(int)
    +Collection<Trayecto> getTrayectosDelMiembro(Miembro)
    +boolean perteneceSector(Sector)
    +void vincularTrabajador(Miembro)
    }

    enum Clasificacion {
    MINISTERIO,
    UNIVERSIDAD,
    ESCUELA,
    ESCUELA_DEL_SECTOR_PRIMARIO,
    ESCUELA_DEL_SECTOR_SECUNDARIO
    }

    enum TipoOrganizacion {
    GUBERNAMENTAL,
    ONG,
    EMPRESA,
    INSTITUCION
    }
}

package "notificadores" #DDDDDD {

    abstract class Notificador {

    +void comunicar(Notificacion, Collection<Contacto>)
    }

    class EmailSender {
    -instance: EmailSender
    -remitente: String
    -password: String

    +EmailSender getInstance()
    +void enviarConGMail(String, String, String)
    }

    enum MedioNotificacion {
    NINGUNO,
    EMAIL,
    WHATSAPP,
    EMAIL_Y_WHATSAPP
    }

    class ManejadorEvento {
    -instancia: ManejadorEvento

    +ManejadorEvento getInstancia()
    +void notificar(Notificacion, Organizacion)
    }

    class NotificarPorWpp extends Notificador {

    }

    class NotificarPorMail extends Notificador {
    - instancia: NotificarPorMail

    +NotificarPorMail getInstancia()
    }

    class Notificacion {
    -asunto: String
    -cuerpo: String
    }
}

package "repositorios" #DDDDDD {

    class RepoOrganizaciones {
    -organizaciones: [Organizacion]
    -instance: RepoOrganizaciones

    +RepoOrganizaciones getInstance()
    +Organizacion encontrarOrganizacion(Area)
    +Collection<Contacto> listadoContactosOrganizaciones()
    +Collection<Area> listadoAreasOrganizaciones()

    }

    class RepoTransportePublico {
    -lineas: <String, [Parada]>
    -instance: RepoTransportePublico

    +RepoTransportePublico getInstance()

    }

    class RepositorioUsuarios {
    -salt: [byte]
    -loginUsuarios: <String,String>
    -instance: RepositorioUsuarios

    +RepositorioUsuarios getInstance()
    +String generarHash(String, byte[])
    +void validarContrasenia(String)
    +void agregarUsuario(String,String)
    +boolean contraseniaCoincide(String, String)
    }

    class RepoLocalidad {
    -localidades: [Localidad]
    -instance: RepoLocalidad

    +RepoLocalidad getInstance()
    }

    class Localidad {

    }
    note right: El modelo de la API está en su propio DC


    class RepoMedioTransporte {
    -mediosDeTransporte: [MedioDeTransporte]
    -instance: RepoMedioTransporte

    +RepoMedioTransporte getInstance()

    }

    class RepoMunicipio {
    -municipios: [Municipio]
    -instance: RepoMunicipio

    +RepoMunicipio getInstance()

    }

    class Municipio {

    }
    note right: El modelo de la API está en su propio DC

    class RepoProvincia {
    -provincias: [Provincia]
    -instance: RepoProvincia

    +RepoProvincia getInstance()

    }

    class Provincia {

    }
    note right: El modelo de la API está en su propio DC

}

package "huellaDeCarbono" #DDDDDD {

    package "CalculadoraHC" {
        class CalculadoraHCActividad {
        -tiposActividad: [TipoActividad]

        -TipoActividad obtenerTipoActividad DatoDeLaActividad)
        +double calcularHuellaCarbonoLogProdRes(Collection DatoDeLaActividad>)
        +double calcularHuellaCarbonoCombElec DatoDeLaActividad)
        +double calcularHCActividadAnual(Collection DatoDeLaActividad>, int)
        +double calcularHCActividadMensual(Collection DatoDeLaActividad>, int, int)
        }

        class TipoActividad {
        -nombre: String
        -fe: double
        -tipoUnidad: String
        }

        class ValorHCMensualMiembro {
        -anio: int
        -mes: int
        -huellaCarbono: double

        +boolean soyMes(int, int)
        }

         class ValorHCMensualOrganizacion{
         -anio: int
         -mes: int
         -huellaCarbono: double
         }

         class ValorHCMensualSector {
         -anio: int
         -mes: int
         -huellaCarbono: double
         -sector: Sector
         }
    }

    package "espacio" {
        abstract class Espacio {
        -latitud: Double
        -longitud: Double
        -provincia: String
        -direccion: String
        -numero: int
        -codigoPostal: int
        -municipio: String
        -localidad: String
        }

        class Hogar extends Espacio {
        -piso: int
        -departamento: String
        -tipoHogar: TipoHogar
        }

        class Parada extends Espacio {

        }

        class EspacioDeTrabajo extends Espacio {
        -piso: int
        -unidad: String
        }

        enum TipoHogar {
        CASA,
        DEPARTAMENTO,
        RESIDENCIA
        }
    }

    package "medioDeTransporte" {

        abstract class MedioDeTransporte {
        #factorEmision: double

        +boolean puedoSerCompartido()
        }

        class VehiculoParticular extends MedioDeTransporte {
        -tipoVehiculo: TipoVehiculo
        -tipoCombustible: TipoCombustible
        }

        enum TipoCombustible {
        GNC,
        NAFTA,
        ELECTRICO,
        GASOIL
        }

        enum TipoVehiculo {
        AUTO,
        MOTO,
        CAMIONETA
        }

        class TransporteNoMotorizado extends MedioDeTransporte {
        -tipoNoMotorizado: TipoNoMotorizado
        }

        enum TipoNoMotorizado {
        BICI,
        A_PIE,
        OTROS
        }

        class ServicioContratado extends MedioDeTransporte {
        -tipoServicioContratado: TipoServicioContratado
        }

        enum TipoServicioContratado {
        TAXI,
        REMIS
        }

        class TransportePublico extends MedioDeTransporte {
        -nombre: String
        -tipoTransportePublico: TipoTransportePublico
        }

        enum TipoTransportePublico {
        TREN,
        SUBTE,
        COLECTIVO
        }
    }

    package "trayecto" {

        class Trayecto {
        -partida: Espacio
        -llegada: Espacio
        -tramos: [Tramo]
        -fechaInicio: LocalDate
        -fechaFin: LocalDate
        -diasUtilizados: int

        +double calcularHuellaCarbonoTotalTrayecto()
        +double calcularHCTrayectoSemanal()
        +double calcularHCTrayectoMensual()
        +boolean perteneceMiembro(Miembro)
        +boolean perteneceMes(int, int)
        +boolean perteneceAnio(int)
        +boolean perteneceMesTrayFin(int, int)
        +boolean perteneceMesTrayNoFin(int, int)
        +double peso()
        }

        class Tramo {
        -partida: Espacio
        -llegada: Espacio
        -transporte: MedioDeTransporte
        -miembros: [Miembro]
        -distancia: double

        +double calcularDistancia()
        +double calcularHuellaCarbonoTramo()
        +boolean tieneMiembro(Miembro)
        }

        class ManejadorTrayectos {
        -instance: ManejadorTrayectos

        +ManejadorTrayectos getInstance()
        +double calcularHCMensual(Collection<Trayecto>, int, int)
        }

        class ServicioApiDistancia {

        }
        note right: El modelo de la API está en su propio DC

    }
}

package "excel_ETL" #DDDDDD {

    class DatoDeLaActividad {
    -actividad:String
    -tipoActividad:TipoActividad
    -consumo:Consumo
    -periodoDeImputacion:String

    +boolean perteneceAnio(int)
    +boolean perteneceMesAnio(int, int)
    +boolean perteneceSoloAnio(int)
    }

    class Consumo {
    -valor: Double
    -periodicidad:String
    }

    class Transformador {
    -datosActividad:  DatoDeLaActividad]

    +void cargarDatos(String)
    }
}

package "roles" #DDDDDD {

    abstract Usuario {
    -usuario: String
    -contraseniaHasheada: String
    +miValidador : ValidadorDeMetricas
    -salt: [byte]

    +String generarHash(String, [byte])
    }


    class Administrador extends Usuario {
    }

    class AgenteSectorial extends Usuario {
    -sectorTerritorial: Sector
    -valoresMensuales:[ValorHCMensualSector]

    +double calcularHuellaCarbonoPorSectorAnual(int)
    +double calcularHuellaCarbonoPorSectorMensual(int, int)
    }

    class UsuarioComun extends Usuario {

    }

    class UsuarioOrganizacion extends Usuario {

    }
}

Miembro ..> Trayecto
Miembro --> Persona
Miembro --> "2" Area
Miembro --> "*" ValorHCMensualMiembro


Area --> EspacioDeTrabajo
Area --> "2*" Miembro
Area --> "2*" Trayecto

Organizacion --> "*" DatoDeLaActividad
Organizacion --> "*" Area
Organizacion --> TipoOrganizacion
Organizacion --> Clasificacion
Organizacion --> "*" Contacto
Organizacion ..> Transformador
Organizacion --> MedioNotificacion
Organizacion ..> ManejadorEvento
Organizacion --> "*" ValorHCMensualOrganizacion
Organizacion --> OrganizacionService
Organizacion --> Usuario

OrganizacionService --> Transformador
OrganizacionService --> CalculadoraHCActividad

Trayecto --> "2" Espacio
Trayecto --> "*" Tramo

DatoDeLaActividad --> Consumo
DatoDeLaActividad --> TipoActividad

Transformador --> "*" DatoDeLaActividad

Tramo --> "2" Espacio
Tramo --> MedioDeTransporte
Tramo --> "*" Miembro
Tramo ..> ServicioApiDistancia

Hogar --> TipoHogar

VehiculoParticular --> TipoVehiculo
VehiculoParticular --> TipoCombustible

ServicioContratado --> TipoServicioContratado

TransportePublico --> TipoTransportePublico

TransporteNoMotorizado --> TipoNoMotorizado

RepositorioUsuarios --> Usuario
RepositorioUsuarios --> RepositorioUsuarios

RepoTransportePublico --> "*" Parada
RepoTransportePublico --> RepoTransportePublico

RepoOrganizaciones --> RepoOrganizaciones
RepoOrganizaciones --> "*" Organizacion

RepoLocalidad --> RepoLocalidad
RepoLocalidad --> "*" Localidad

RepoMedioTransporte --> RepoMedioTransporte
RepoMedioTransporte --> "*" MedioDeTransporte

RepoMunicipio --> RepoMunicipio
RepoMunicipio --> "*" Municipio

RepoProvincia --> RepoProvincia
RepoProvincia --> "*" Provincia

ManejadorTrayectos --> ManejadorTrayectos

Persona --> Hogar
Persona --> Usuario
Persona --> TipoDocumento

CalculadoraHCActividad --> "*" TipoActividad

Notificador ..> Notificacion
Notificador ..> Contacto

ManejadorEvento --> ManejadorEvento
ManejadorEvento ..> Notificador

AgenteSectorial ..> RepoOrganizaciones
AgenteSectorial --> Sector

ProvinciaSector --> PaisSector
MunicipioSector --> ProvinciaSector
LocalidadSector --> MunicipioSector

NotificarPorMail ..> EmailSender
NotificarPorMail --> NotificarPorMail

EmailSender --> EmailSender

Sector --> "*" ValorHCMensualSector


@enduml