@startuml
skinparam classAttributeIconSize 0


package "verificadorSesion" #DDDDDD {
    class VerificadorInicioSesion {
    -intentoUsuarios: <String, IntentosInicioSesion>

    +Usuario loggearUsuario(String, String)
    }

    class IntentoInicioSesion {
    -usuario: String
    -cantIntentos: int
    -timestamp: long

    +void aumentarIntentos()
    +boolean puedeIntentarLoggearse()
    }
}


package "roles" #DDDDDD {
    class Usuario {
    -usuario: String
    -contrasenia: String
    -esAdministrador: boolean
    }
}

package "password" #DDDDDD {
    class ValidadorDeMetricas {
    -validadores: [ValidadorContrasenia]

    +String validarTodo(String, String)
    }

    abstract class ValidadorContrasenia {
    #mensajeError: String

    + void validar(String, String)
    + boolean condicionInvalidez(String, String)
    }

    class ValidadorDeCaracteres extends ValidadorContrasenia {

    +boolean caracterEsValido(int , int)
    +boolean caracterValidoAscii(int)
    +boolean caracterValidoUNICODE(int)
    }

    class ValidadorContraseniaComun extends ValidadorContrasenia {

    }

    class ValidadorContraseniaNoContieneUsuario extends ValidadorContrasenia {

    }

    class ValidadorLongitudContrasenia extends ValidadorContrasenia {

    }

    class ValidadorDeEspacio {

    +String contraseniaSinEspacios(String)
    }
}



VerificadorInicioSesion --> IntentoInicioSesion
VerificadorInicioSesion ..> Usuario

Usuario --> ValidadorDeMetricas

ValidadorDeMetricas --> "*" ValidadorContrasenia
ValidadorDeMetricas ..> ValidadorDeEspacio

@enduml