@startuml
skinparam classAttributeIconSize 0

package "miembro" #DDDDDD {
    class Persona {
    -nombre: String
    -apellido: String
    -nroDocumento: String
    -tipoDocumento: TipoDocumento
    -ubicacion: Hogar
    -usuario: Usuario
    }

    class Miembro {
    -persona: Persona
    -area: Area

    +Double calcularHuellaCarbonoMiembro()
    +void cargarTrayecto(Trayecto)
    +Double impactoMiembroEnOrganizacion(Double)
    }

    class AgenteSectorial extends Persona {
    -sectorTerritorial: String

    +Double huellaDeCarbonoPorSector(LocalDate, boolean)
    -boolean perteneceASector(Area)
    }

    enum TipoDocumento {
    DNI,
    LE,
    LC
    }
}

package "organizacion" #DDDDDD {

    class Contacto {
    -mail: String
    -numeroTelefono: String
    }

    class Organizacion {
    -razonSocial: String
    -tipo: TipoOrganizacion
    -clasificacion: Clasificacion
    -sectores: [Area]
    -transformador: Transformador
    -contactos: [Contacto]
    -calculadora: CalculadoraHCActividad

    +void agregarArea(Area)
    +Double calcularHuellaCarbonoTotalFecha(LocalDate, Double, boolean)
    +Double calcularHuellaCarbonoSectorial(Double, String)
    +boolean tieneArea(Area)
    +void agregarContacto(String, String)
    }

    class Area {
    -nombre: String
    -miembros: [Miembro]
    -ubicacion: EspacioDeTrabajo
    -trayectosRegistrados: [Trayecto]
    -trayectosPendientes: [Trayecto]

    +void registrarMiembro(Miembro)
    +void aceptarVinculacion(Trayecto)
    +void agregarVinculacion(Trayecto)
    +Double calcularHuellaCarbonoTotalArea(LocalDate, boolean)
    +List<Trayecto> getTrayectosDelMiembro(Miembro)
    +Double calcularHuellaCarbonoPromedioMiembro(LocalDate, boolean)
    }

    enum Clasificacion {
    MINISTERIO,
    UNIVERSIDAD,
    ESCUELA,
    ESCUELA_DEL_SECTOR_PRIMARIO,
    ESCUELA_DEL_SECTOR_SECUNDARIO
    }

    enum TipoOrganizacion {
    GUBERNAMENTAL,
    ONG,
    EMPRESA,
    INSTITUCION
    }
}

package "notificadores" #DDDDDD {

    class Notificador {
    -mailGeneral: String
    -numeroGeneral: String
    -password: String
    -emailSender: EmailSender
    -whatsappSender: WhatsappSender

    +void execute(JobExecutionContext)
    +void enviarNotificacionesPorTodosLosMedios(String, String)
    }

    class EmailSender {
    -prop: Properties
    -session: Session
    -username: String
    -password: String

    +void send(String, String, String, String)
    }

    class WhatsappSender {

    +void send(String, String, String, String)
    }
}

package "repositorios" #DDDDDD {

    class RepoOrganizaciones {
    -organizaciones: [Organizacion]
    -instance: RepoOrganizaciones

    +Organizacion encontrarOrganizacion(Area)
    +List<Contacto> listadoContactosOrganizaciones()
    +List<Area> listadoAreasOrganizaciones()

    }

    class RepoTransportePublico {
    -lineas: <String, [Parada]>
    -instance: RepoTransportePublico

    }

    class RepositorioUsuarios {
    -salt: [byte]
    -loginUsuarios: <String,String>
    -instance: RepositorioUsuarios

    +String generarHash(String, byte[])
    +void validarContrasenia(String)
    +void agregarUsuario(String,String)
    +boolean contraseniaCoincide(String, String)
    }
}

package "huellaDeCarbono" #DDDDDD {

    class CalculadoraHCActividad {
    -factorEmisionGas: Double
    -factorEmisionDiesel: Double
    -factorEmisionKerosene: Double
    -factorEmisionFuel: Double
    -factorEmisionNafta: Double
    -factorEmisionCarbon: Double
    -factorEmisionCarbonLenia: Double
    -factorEmisionLenia: Double
    -factorEmisionCombConsumidoGasoil: Double
    -factorEmisionCombConsumidoGNC: Double
    -factorEmisionCombConsumidoNafta: Double
    -factorEmisionElectricidad: Double
    -factorEmisionLogProdRes: Double

    +Double calcularHuellaCarbonoLogProdRes(List<DatosDeLaActividad>, Double)
    +Double calcularHuellaCarbonoCombElec(DatosDeLaActividad)
    +Double calcularHCActividad(List<DatosDeLaActividad>, LocalDate, boolean, Double)
    -Double obtenerFE(String)
    }

    package "espacio" {
        abstract class Espacio {
        -latitud: Double
        -longitud: Double
        -provincia: String
        -direccion: String
        -numero: int
        -codigoPostal: int
        -barrio: String
        -municipio: String
        -localidad: String
        }

        class Hogar extends Espacio {
        -piso: int
        -departamento: String
        -tipoHogar: TipoHogar
        }

        class Parada extends Espacio {

        }

        class EspacioDeTrabajo extends Espacio {
        -piso: int
        -unidad: String
        }

        enum TipoHogar {
        CASA,
        DEPARTAMENTO,
        RESIDENCIA
        }
    }

    package "medioDeTransporte" {

        abstract class MedioDeTransporte {
        -factorEmision: Double

        +boolean puedoSerCompartido()
        }

        class VehiculoParticular extends MedioDeTransporte {
        -tipoVehiculo: TipoVehiculo
        -tipoCombustible: TipoCombustible
        }

        enum TipoCombustible {
        GNC,
        NAFTA,
        ELECTRICO,
        GASOIL
        }

        enum TipoVehiculo {
        AUTO,
        MOTO,
        CAMIONETA
        }

        class TransporteNoMotorizado extends MedioDeTransporte {
        -tipoNoMotorizado: TipoNoMotorizado
        }

        enum TipoNoMotorizado {
        BICI,
        A_PIE,
        OTROS
        }

        class ServicioContratado extends MedioDeTransporte {
        -tipoServicioContratado: TipoServicioContratado
        }

        enum TipoServicioContratado {
        TAXI,
        REMIS
        }

        class TransportePublico extends MedioDeTransporte {
        -nombre: String
        -tipoTransportePublico: TipoTransportePublico
        }

        enum TipoTransportePublico {
        TREN,
        SUBTE,
        COLECTIVO
        }
    }

    package "trayecto" {

        class Trayecto {
        -partida: Espacio
        -llegada: Espacio
        -tramos: [Tramo]
        -fechaInicio: LocalDate

        +Double calcularHuellaCarbonoTotalTrayecto()
        +boolean perteneceMiembro(Miembro)
        +boolean perteneceMes(LocalDate)
        +boolean perteneceAnio(LocalDate)
        }

        class Tramo {
        -partida: Espacio
        -llegada: Espacio
        -transporte: MedioDeTransporte
        -miembros: [Miembro]
        -periodicidad: Double

        +Double calcularDistancia()
        +void agregarMiembro(Miembro, Double)
        +Double calcularHuellaCarbonoTramo()
        +boolean tieneMiembro(Miembro)
        +Double getPeriodicidad()
        }

        class ServicioApiDistancia {

        }
        note right: El modelo de la API está en su propio DC

    }
}

package "excel_ETL" #DDDDDD {

    class DatosDeLaActividad {
    -actividad:String
    -tipoDeConsumo:String
    -consumo:Consumo
    -periodoDeImputacion:String

    }

    class Consumo {
    -valor: Double
    -periodicidad:String
    }

    class Transformador {
    -datosActividad: [DatosDeLaActividad]

    +void cargarDatos(String)
    }
}

package "roles" #DDDDDD {

    abstract Usuario {
    -usuario: String
    +miValidador : ValidadorDeMetricas
    }

    class UsuarioComun extends Usuario {
    }

    class Administrador extends Usuario {
    -calculadoraHCActividad: CalculadoraHCActividad

      +void setFactorEmisionFuel(Double)
      +void setFactorEmisionDiesel(Double)
      +void setFactorEmisionGas(Double)
      +void setFactorEmisionNafta(Double)
      +void setFactorEmisionLogProdRes(Double)
      +void setFactorEmisionCarbon(Double)
      +void setFactorEmisionCarbonLenia(Double)
      +void setFactorEmisionElectricidad(Double)
      +void setFactorEmisionKerosene(Double)
      +void setFactorEmisionLenia(Double)
      +void setFactorEmisionCombConsumidoGasoil(Double)
      +void setFactorEmisionCombConsumidoGNC(Double)
      +void setFactorEmisionCombConsumidoNafta(Double)
    }
}

Miembro ..> Trayecto

Area --> EspacioDeTrabajo
Area --> "*" Miembro
Area --> "2*" Trayecto

Organizacion --> "*" Area
Organizacion --> TipoOrganizacion
Organizacion --> Clasificacion
Organizacion --> Transformador
Organizacion --> "*" Contacto
Organizacion --> CalculadoraHCActividad

Trayecto --> "2" Espacio
Trayecto --> "*" Tramo

DatosDeLaActividad --> Consumo

Transformador --> "*" DatosDeLaActividad

Tramo --> "2" Espacio
Tramo --> MedioDeTransporte
Tramo --> "*" Miembro
Tramo ..> ServicioApiDistancia

Hogar --> TipoHogar

VehiculoParticular --> TipoVehiculo
VehiculoParticular --> TipoCombustible

ServicioContratado --> TipoServicioContratado

TransportePublico --> TipoTransportePublico

TransporteNoMotorizado --> TipoNoMotorizado

RepositorioUsuarios --> Usuario
RepositorioUsuarios --> RepositorioUsuarios

RepoTransportePublico --> "*" Parada
RepoTransportePublico --> RepoTransportePublico

RepoOrganizaciones --> RepoOrganizaciones
RepoOrganizaciones --> "*" Organizacion

Miembro --> Persona

Persona --> Hogar
Persona --> Usuario
Persona --> TipoDocumento

Administrador --> CalculadoraHCActividad

Notificador --> WhatsappSender
Notificador --> EmailSender
Notificador ..> RepoOrganizaciones

AgenteSectorial ..> RepoOrganizaciones

@enduml